# Generated by Django 4.0.5 on 2022-06-25 09:38

from django.db import migrations, models
import downloader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_created=True)),
                ('link', models.CharField(max_length=255)),
                ('video_id', models.CharField(max_length=15)),
                ('expire_time', models.DateTimeField()),
                ('file_type', models.CharField(choices=[('A', 'Audio'), ('L', 'Low Quality Video'), ('H', 'High Quality Video')], max_length=2)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
